[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm --filter @csp/db exec prisma generate",
  "pnpm --filter @csp/web build"
]

[start]
cmd = "cd apps/web && pnpm start"