ALTER TABLE "users"
ADD COLUMN "isOnline" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "checkedInAt" TIMESTAMP(3),
ADD COLUMN "checkedOutAt" TIMESTAMP(3),
ADD COLUMN "engineerStatus" TEXT NOT NULL DEFAULT 'FREE';
